ToDoApp/TaskManagementApp/TaskApp/urls.py
from django.urls import path
from .views import (
    TaskListView, TaskDetailView,
    TaskCreateView, TaskDeleteView, TaskUpdateView, HomeView)

app_name = "TaskApp"

urlpatterns = [
    path('list/', TaskListView.as_view(), name='list'),
    path('detail/<int:pk>/', TaskDetailView.as_view(), name='detail'),
    path('create/', TaskCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', TaskUpdateView.as_view(), name='update'),
    path('home/', HomeView.as_view(), name='home'),
]

ToDoApp/TaskManagementApp/TaskManagementProject/urls.py
from django.contrib import admin
from django.urls import path, include
from TaskApp.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name='home'),
    path('userapp/', include('UserApp.urls', namespace='UserApp')),
    path('taskapp/', include('TaskApp.urls', namespace='TaskApp')),
]

ToDoApp/TaskManagementApp/UserApp/urls.py
from django.urls import path, reverse_lazy
from .views import UserLoginView, SignUpView
from django.contrib.auth.views import LogoutView

app_name = 'UserApp'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('TaskApp:home')), name='logout'),
]

ToDoApp/TaskManagementApp/TaskApp/models.py
from django.db import models
from UserApp.models import CustomUser


class Priority(models.Model):
    HIGH = '高'
    MEDIUM = '中'
    LOW = '低'
    CHOICES = [
        (HIGH, 'High'),
        (MEDIUM, 'Medium'),
        (LOW, 'Low'),
    ]

    name = models.CharField(max_length=50, choices=CHOICES)

    def __str__(self):
        return self.name


class Task(models.Model):
    task_name = models.CharField(max_length=100)
    task_detail = models.TextField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)
    priority = models.ForeignKey(Priority, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task_name

ToDoApp/TaskManagementApp/UserApp/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, UserManager)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    birthday = models.DateField(null=True, blank=True)
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'

ToDoApp/TaskManagementApp/TaskApp/forms.py
from django import forms
from .models import Task, Priority


class TaskCreateForm(forms.ModelForm):
    priority = forms.ModelChoiceField(
        queryset=Priority.objects.all(),
        empty_label="優先度を選択",
        label="優先度"
    )

    due_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=False,
        label="期限"
    )

    class Meta:
        model = Task
        fields = ['task_name', 'task_detail', 'due_date', 'priority']


class TaskUpdateForm(forms.ModelForm):
    priority = forms.ModelChoiceField(
        queryset=Priority.objects.all(),
        empty_label="優先度を選択",
        label="優先度")

    due_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=False,
        label='期限'
    )

    class Meta:
        model = Task
        fields = ['task_name', 'task_detail', 'due_date',
                  'is_completed', 'priority']

ToDoApp/TaskManagementApp/UserApp/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(
        label="姓",
        widget=forms.TextInput(
        attrs={'class': 'form-control', },))
    last_name = forms.CharField(
        label="名",
        widget=forms.TextInput(
        attrs={'class': 'form-control', },
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control', },
    ))
    birthday = forms.DateField(
        label="誕生日",
        widget=forms.widgets.DateInput(
        attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd ', 'class': 'form-control',},)
        )
    password1 = forms.CharField(
        label="パスワード",
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', },
            ))
    password2 = forms.CharField(
        label="パスワード再入力",
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', },
            ))

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'birthday')

ToDoApp/TaskManagementApp/TaskApp/views.py
from django.views.generic import (
    CreateView, ListView, DetailView,
    UpdateView, DeleteView, TemplateView)
from django.urls import reverse_lazy
from .models import Task, Priority
from .forms import TaskCreateForm, TaskUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin


class TaskListView(ListView):
    template_name = 'task_list.html'
    model = Task

    def get_queryset(self):
        sort_param = self.request.GET.get('sort')
        queryset = super().get_queryset()

        if sort_param == 'updated_at':
            queryset = queryset.order_by('updated_at')
        elif sort_param == 'due_date':
            queryset = queryset.order_by('due_date')
        elif sort_param == 'priority':
            queryset = queryset.order_by('priority')

        return queryset


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskCreateForm
    template_name = 'task_create.html'
    success_url = reverse_lazy('TaskApp:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'task_detail.html'


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskUpdateForm
    template_name = 'task_update.html'

    def get_success_url(self):
        return reverse_lazy('TaskApp:detail', kwargs={'pk': self.object.pk})


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'task_delete.html'
    success_url = reverse_lazy('TaskApp:list')


class HomeView(TemplateView):
    template_name = ('home.html')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['login_url'] = reverse_lazy('UserApp:login')

        return context

ToDoApp/TaskManagementApp/UserApp/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm
from django.contrib.auth.views import LoginView, LogoutView


class UserLoginView(LoginView):
    template_name = 'login.html'
    success_url = reverse_lazy('TaskApp:list')


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('UserApp:login')

ToDoApp/TaskManagementApp/TaskApp/templates/home.html
{% extends "task_base.html" %}

{% block title %}
ToDoアプリ
{% endblock title %}

{% block header %}
<div>
    <h1>ToDo管理</h1>
</div>
{% endblock header%}

{% block content %}
<div>
    <p> すでにアカウントをお持ちの方はこちら！</p>
    <a href="{% url 'UserApp:login' %}" class="btn btn-secondary mb-3" tabindex="-1" role="botton" aria-disabled="True">ログイン</a>
    <p>アカウントをまだお持ちでない方はこちら！
    <a href="{% url 'UserApp:signup' %}" class="btn btn-secondary mb-3" tabindex="-1" role="botton" aria-disabled="True">サインアップ</a>
</div>
{% endblock %}

ToDoApp/TaskManagementApp/TaskApp/templates/task_base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <style>
      body {
        background-color: #f7f7f7;
        font-family: 'Yu Gothic', YuGothic, sans-serif;
      }
    </style>

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block header %}
    {% endblock header %}

    {% block content %}
    <div style="padding-left: 32px;">
      {% block inner_content %}
      {% endblock inner_content %}
    {% endblock content %}
  </body>
</html>

ToDoApp/TaskManagementApp/TaskApp/templates/task_create.html
{% extends "task_base.html" %}
{% block title %}
ToDoリスト新規作成画面
{% endblock title %}

{% block header %}
<div>
    <strong>"{{ request.user }}"さん</strong>
    <h1>Task作成</h1>
</div>
{% endblock header %}

{% block content %}
<form action="" method="POST" class="task-form">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
            <small style="color: gray">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
            <small style="color: red">{{ error }}</small>
        {% endfor %}
    </p>
    {% endfor %}
    <button type="submit" value="作成" style="margin-bottom: 16px;">作成</button>
</form>
<a href="{% url 'TaskApp:list' %}">戻る</a>
{% endblock content %}

ToDoApp/TaskManagementApp/TaskApp/templates/task_delete.html
{% extends "task_base.html" %}
{% block title %}
削除画面
{% endblock title %}

{% block header %}
<div>
    <strong>"{{ request.user }}"さん</strong>
    <h1>Delete</h1>
</div>
{% endblock header %}

{% block content %}
<form action="" method="POST">
{% csrf_token %}
<p><strong style="color: red;">{{ task.task_name }}</strong>を本当に削除しますか</p>
<input type="submit" value="削除">
</form>
<a href="{% url 'TaskApp:list' %}" style="display: block; margin-top: 1em">戻る</a>
{% endblock content %}

ToDoApp/TaskManagementApp/TaskApp/templates/task_detail.html
{% extends "task_base.html" %}
{% block title %}詳細画面{% endblock title %}

{% block header %}
<div>
    <strong>"{{ request.user }}" さん</strong>
    <h1>Detail</h1>
</div>
{% endblock header %}

{% block inner_content %}
<div class="container">
    <div class="alert {{ task.priority.get_alert_class }}" role="alert">
        <h4>タスク：</h4>
        <ul>
            {{ task.task_name }}
        </ul>
        <h4>詳細：</h4>
        <ul>
            {{ task.task_detail|linebreaks }}
        </ul>
    </div>

    <a href="{% url 'TaskApp:list' %}" class="btn btn-secondary">戻る</a>
</div>
{% endblock inner_content %}

ToDoApp/TaskManagementApp/TaskApp/templates/task_list.html
{% extends "task_base.html" %}
{% block title %}リスト一覧{% endblock title %}

{% block header %}
<div>
    <strong >"{{ request.user }}" さん</strong>
    <h1>TodoList</h1>
</div>
{% endblock header %}

{% block content %}
<div class="container" >
    <a href="{% url 'TaskApp:create' %}" class="btn btn-secondary mb-3" tabindex="-1" role="button" aria-disabled="true">新規タスク作成</a>
    
    <div>
        <a href="{% url 'TaskApp:list' %}?sort=date_created">作成日でソート</a>
        <a href="{% url 'TaskApp:list' %}?sort=date_updated">更新日でソート</a>
        <a href="{% url 'TaskApp:list' %}?sort=priority">優先度でソート</a>
    </div>

    {% for task in task_list %}
    <div class="alert {{ task.priority.get_alert_class }}" role="alert">
        <p>
            【作成日：{{ task.created_at|date:"Y/m/d" }}（最終更新日：{{ task.updated_at|date:"Y/m/d" }}）】
        </p>
       {#<form method="POST" action="{% url 'TaskApp:update' pk=task.pk %}"> #}
        {#{% csrf_token %} #}
        {#<input type="checkbox" name="is_completed" {% if task.is_completed %}checked{% endif %} onchange="this.form.submit()">#}
        {% if task.is_completed %}
        <p>
            ✔完了：<s>{{ task.task_name }}</s>
            <s><span class="task-date">(期日：{{ task.due_date|date:"Y/m/d" }})</span></s>
        </p>
        {% else %}
        <p class="task-name">
            {{ task.task_name }}
            <span class="">(優先度: {{ task.priority.name }})</span>
            <span class="task-date">(期日：{{ task.due_date|date:"Y/m/d" }})</span>
        <p>
        {% endif %}
        <a href="{% url 'TaskApp:update' pk=task.pk %}" class="btn btn-outline-secondary" tabindex="-1" role="button" aria-disabled="true">編集</a>
        <a href="{% url 'TaskApp:detail' pk=task.pk %}" class="btn btn-outline-secondary" tabindex="-1" role="button" aria-disabled="true">詳細</a>
        <a href="{% url 'TaskApp:delete' pk=task.pk %}" class="btn btn-outline-secondary" tabindex="-1" role="button" aria-disabled="true">削除</a>
    </div>
    {% endfor %}
    <form action="{% url 'UserApp:logout' %}" method="post" style="margin: 32px 0;">
    {% csrf_token %}
        <input type="submit" value="ログアウト" class="btn btn-secondary">
    </form>
</div>
{% endblock content %}

ToDoApp/TaskManagementApp/TaskApp/templates/task_update.html
{% extends "task_base.html" %}
{% block title %}編集画面{% endblock title %}

{% block header %}
<div>
    <strong>"{{ request.user }}" さん</strong>
    <h1>Taskの編集</h1>
</div>
{% endblock header %}

{% block content %}
<form method="POST" >
    {% csrf_token %}
    {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </p>
    {% endfor %}
    <button type="submit" value="更新" style="margin-bottom: 16px;">更新</button>
</form>
<a href="{% url 'TaskApp:list' %}" style="display: block; margin-top: 1em;">戻る</a>

{% endblock content %}

ToDoApp/TaskManagementApp/TaskApp/templates/taskapp/home.html
{% extends "TaskApp/templates/taskapp/task_base.html" %}

{% block title %}
ToDoアプリ
{% endblock title %}

{% block header %}
<div>
    <h1>ToDo管理</h1>
</div>
{% endblock header%}

{% block content %}
<div>
    <p> すでにアカウントをお持ちの方はこちら！</p>
    <a href="{% url 'login' %}" class="btn btn-secondary mb-3" tabindex="-1" role="botton" aria-disabled="True">ログイン</a>
    <p>アカウントをまだお持ちでない方はこちら！
    <a href="{% url 'signup' %}" class="btn btn-secondary mb-3" tabindex="-1" role="botton" aria-disabled="True">サインアップ</a>
</div>
{% endblock %}

ToDoApp/TaskManagementApp/TaskApp/templates/taskapp/task_create.html
{% extends "TaskApp/templates/taskapp/task_base.html" %}
{% block title %}
新規作成画面
{% endblock title %}

{% block header %}
<div>
    <strong>"{{ request.user }}"さん</strong>
    <h1>Create</h1>
</div>
{% endblock header %}

{% block content %}

<form action="" method="POST" class="task-form">
    {% csrf_token %}
    {{%% for field in form %}}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
            <small style="color: gray">{{ field.help_text }}</small>
        {{% endif %}}
        {% for error in field.errors %}
            <small style="color: red">{{ error }}</small>
        {% endfor %}
    </p>
    {% endfor %}
    <button type="submit" value="作成" style="margin-bottom: 16px;">作成</button>
</form>
<a href="{% url 'taskapp:list' %}">戻る</a>
{% endblock content %}

ToDoApp/TaskManagementApp/TaskApp/templates/taskapp/task_delete.html
{% extends "TaskApp/templates/taskapp/task_base.html" %}
{% block title %}
削除画面
{% endblock title %}

{% block header %}
<div>
    <strong>"{{ request.user }}"さん</strong>
    <h1>Delete</h1>
</div>
{% endblock header %}

{% block content %}
<form action="" method="POST">
{% csrf_token %}
<p><strong style="color: red;">{{ task.task_name }}</strong>を本当に削除しますか</p>
<input type="submit" value="削除">
</form>
<a href="{% url 'taskapp:list' %}" style="display: block; margin-top: 1em">戻る</a>
{% endblock content %}

ToDoApp/TaskManagementApp/TaskApp/templates/taskapp/task_detail.html
{% extends "TaskApp/templates/taskapp/task_base.html" %}
{% block title %}詳細画面{% endblock title %}

{% block header %}
<div>
    <strong>"{{ request.user }}" さん</strong>
    <h1>Detail</h1>
</div>
{% endblock header %}

{% block inner_content %}
<div class="container">
    <div class="alert {{ task.priority.get_alert_class }}" role="alert">
        <h4>タスク：</h4>
        <ul>
            {{ task.task_name }}
        </ul>
        <h4>詳細：</h4>
        <ul>
            {{ task.task_detail|linebreaks }}
        </ul>
    </div>

    <a href="{% url 'taskapp:list' %}" class="btn btn-secondary">戻る</a>
</div>
{% endblock inner_content %}

ToDoApp/TaskManagementApp/TaskApp/templates/taskapp/task_list.html
{% extends "TaskApp/templates/taskapp/task_base.html" %}
{% block title %}リスト一覧{% endblock title %}

{% block header %}
<div>
    <strong >"{{ request.user }}" さん</strong>
    <h1>TodoList</h1>
</div>
{% endblock header %}

{% block content %}
<div class="container" >
    <a href="{% url 'taskapp:create' %}" class="btn btn-secondary mb-3" tabindex="-1" role="button" aria-disabled="true">新規タスク作成</a>
    
    <div>
        <a href="{% url 'list' %}?sort=date_created">作成日でソート</a>
        <a href="{% url 'list' %}?sort=date_updated">更新日でソート</a>
        <a href="{% url 'list' %}?sort=priority">優先度でソート</a>
    </div>

    {% for task in task_list %}
    <div class="alert {{ task.priority.get_alert_class }}" role="alert">
        <p>
            【作成日：{{ task.created_at|date:"Y/m/d" }}（最終更新日：{{ task.updated_at|date:"Y/m/d" }}）】
        </p>
        {% if task.is_completed %}
        <p>
            ✔完了：<s>{{ task.task_name }}</s>
            <s><span class="task-date">(期日：{{ task.due_date|date:"Y/m/d" }})</span></s>
        </p>
        {% endif %}
        <a href="{% url 'update' task.pk %}" class="btn btn-outline-secondary" tabindex="-1" role="button" aria-disabled="true">編集</a>
        <a href="{% url 'detail' task.pk %}" class="btn btn-outline-secondary" tabindex="-1" role="button" aria-disabled="true">詳細</a>
        <a href="{% url 'delete' task.pk %}" class="btn btn-outline-secondary" tabindex="-1" role="button" aria-disabled="true">削除</a>
    </div>
    {% endfor %}
    <form action="{% url 'taskapp:logout' %}" method="post" style="margin: 32px 0;">{% csrf_token %}
        <input type="submit" value="ログアウト" class="btn btn-secondary">
    </form>
</div>
{% endblock content %}

ToDoApp/TaskManagementApp/TaskApp/templates/taskapp/task_update.html
{% extends "TaskApp/templates/taskapp/task_base.html" %}
{% block title %}編集画面{% endblock title %}

{% block header %}
<div>
    <strong>"{{ request.user }}" さん</strong>
    <h1>Update</h1>
</div>
{% endblock header %}

{% block content %}
<form method="POST" >
    {% csrf_token %}
    {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </p>
    {% endfor %}
    <button type="submit" value="更新" style="margin-bottom: 16px;">更新</button>
</form>
<a href="{% url 'list' %}" style="display: block; margin-top: 1em;">戻る</a>

{% endblock content %}

ToDoApp/TaskManagementApp/UserApp/templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    
    <title>{% block title %}{% endblock title %}</title>
    
  </head>
  <body>
    {% block header %}
    {% endblock header %}

    <div style="padding-left: 32px;">
      {% block content %}
      {% block inner_content %}
      {% endblock inner_content %}
      {% endblock content %}
  </body>
</html>

ToDoApp/TaskManagementApp/UserApp/templates/login.html
{% extends "base.html" %}
{% block title %}ログイン画面{% endblock title %}

{% block header %}
<div class>
    <h1>ログイン</h1>
</div>
{% endblock header %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>
        {{ form.username.label_tag }}<br>
        {{ form.username }}
        {% for error in form.username.errors %}
            <small style="color: red">{{ error }}</small>
        {% endfor %}
    </p>
    
    <p>
        {{ form.password.label_tag }}<br>
        {{ form.password }}
        {% for error in form.password.errors %}
            <small style="color: red">{{ error }}</small>
        {% endfor %}
    </p>
    <button type="submit" class="btn btn-primary">ログイン</button>
</form>


<p>アカウントを持っていない方はこちらから<a href="{% url 'UserApp:signup' %}">新規登録</a>をしてください。</p>

<!-- ホーム画面へのリンク -->
<a href="{% url 'TaskApp:home' %}" class="btn btn-secondary">戻る</a>
{% endblock content %}

ToDoApp/TaskManagementApp/UserApp/templates/signup.html
{% extends "base.html" %}
{% block title %}新規登録画面{% endblock title %}

{% block header %}
<div>
    <h1>新規ユーザー登録フォーム</h1>
</div>
{% endblock header %}

{% block content %}
<form method="post" class="signup-form">
    {% csrf_token %}
    {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </p>
    {% endfor %}
    <button type="submit">登録</button>
</form>
<a href="{% url 'TaskApp:home' %}">戻る</a>
{% endblock content %}

ToDoApp/TaskManagementApp/UserApp/templates/userapp/login.html
{% extends "base.html" %}
{% block title %}ログイン画面{% endblock title %}

{% block header %}
<div class>
    <h1>ログイン</h1>
</div>
{% endblock header %}

{% block content %}
<form method="post" action="{% url 'userapp:login' %}">
    {% csrf_token %}
    <p>
        {{ form.username.label_tag }}<br>
        {{ form.username }}
        {% for error in form.username.errors %}
            <small style="color: red">{{ error }}</small>
        {% endfor %}
    </p>
    
    <p>
        {{ form.password.label_tag }}<br>
        {{ form.password }}
        {% for error in form.password.errors %}
            <small style="color: red">{{ error }}</small>
        {% endfor %}
    </p>
    <button type="submit" class="btn btn-primary">ログイン</button>
</form>


<p>アカウントを持っていない方はこちらから<a href="{% url 'signup' %}">新規登録</a>をしてください。</p>

<!-- ホーム画面へのリンク -->
<a href="{% url 'home' %}" class="btn btn-secondary">戻る</a>
{% endblock content %}